AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GreetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: my_module/
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        GreetGET:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        GreetPOST:
          Type: Api
          Properties:
            Path: /hello
            Method: post
