AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: my_module/
      Handler: main.lambda_handler
      Runtime: python3.11
      Events:
        GreetByQuery:
          Type: Api
          Properties:
            Path: /greet
            Method: get
        GreetByPath:
          Type: Api
          Properties:
            Path: /greet/{name}
            Method: get
